input {
    beats {
        port => 5044
    }
}

filter {
    if [container][name] =~ "web" {
        json {
            source => "message"
        }
    }
}

output {
    elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "docker-logs-%{+YYYY.MM.dd}"
    }
}